spring:
  application:
    name: gateway-service
  cloud:
   gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: productsAPI
        uri: lb://products-api
        predicates:
          - Path=/products/**
        filters:
          - RewritePath=/products/*, /
          
      - id: ordersAPI
        uri: lb://orders-api
        predicates:
          - Path=/orders/**
        filters:
          - RewritePath=/orders/*, /      
server:
  port: 9000
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka



